### PR TITLE
Update modDesc.xml

### PR DESCRIPTION
**Pull request by vitalii2011**

### CODE REVIEW

**Comment by Percedal** [comment]
i updated moddesc to the latest mod version. you may check that and redo your PR, thanks

**Comment by vitalii2011** [comment]
thx. added a little. )

**Comment by Percedal** [comment]
Somehow, moddesc on your branch do not contain l10n "uf_max_level", so for consistency can you translate "Your production is already at maximum level.". No need for a PR, juste reply in comment. I already taken into account your contribution.
Thx in advance.

**Comment by vitalii2011** [comment]
`Ваше производство уже на максимальном уровне.`

**Pull request closed without merging**
